/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.cognitiveservices.language.textanalytics.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The DocumentStatistics model.
 */
public class DocumentStatistics {
    /**
     * Number of text elements recognized in the document.
     */
    @JsonProperty(value = "charactersCount")
    private Integer charactersCount;

    /**
     * Number of transactions for the document.
     */
    @JsonProperty(value = "transactionsCount")
    private Integer transactionsCount;

    /**
     * Get number of text elements recognized in the document.
     *
     * @return the charactersCount value
     */
    public Integer charactersCount() {
        return this.charactersCount;
    }

    /**
     * Set number of text elements recognized in the document.
     *
     * @param charactersCount the charactersCount value to set
     * @return the DocumentStatistics object itself.
     */
    public DocumentStatistics withCharactersCount(Integer charactersCount) {
        this.charactersCount = charactersCount;
        return this;
    }

    /**
     * Get number of transactions for the document.
     *
     * @return the transactionsCount value
     */
    public Integer transactionsCount() {
        return this.transactionsCount;
    }

    /**
     * Set number of transactions for the document.
     *
     * @param transactionsCount the transactionsCount value to set
     * @return the DocumentStatistics object itself.
     */
    public DocumentStatistics withTransactionsCount(Integer transactionsCount) {
        this.transactionsCount = transactionsCount;
        return this;
    }

}
