/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.cognitiveservices.language.textanalytics.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The KeyPhraseBatchResultItem model.
 */
public class KeyPhraseBatchResultItem {
    /**
     * Unique, non-empty document identifier.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * A list of representative words or phrases. The number of key phrases
     * returned is proportional to the number of words in the input document.
     */
    @JsonProperty(value = "keyPhrases", access = JsonProperty.Access.WRITE_ONLY)
    private List<String> keyPhrases;

    /**
     * (Optional) if showStats=true was specified in the request this field
     * will contain information about the document payload.
     */
    @JsonProperty(value = "statistics")
    private DocumentStatistics statistics;

    /**
     * Get unique, non-empty document identifier.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set unique, non-empty document identifier.
     *
     * @param id the id value to set
     * @return the KeyPhraseBatchResultItem object itself.
     */
    public KeyPhraseBatchResultItem withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get a list of representative words or phrases. The number of key phrases returned is proportional to the number of words in the input document.
     *
     * @return the keyPhrases value
     */
    public List<String> keyPhrases() {
        return this.keyPhrases;
    }

    /**
     * Get (Optional) if showStats=true was specified in the request this field will contain information about the document payload.
     *
     * @return the statistics value
     */
    public DocumentStatistics statistics() {
        return this.statistics;
    }

    /**
     * Set (Optional) if showStats=true was specified in the request this field will contain information about the document payload.
     *
     * @param statistics the statistics value to set
     * @return the KeyPhraseBatchResultItem object itself.
     */
    public KeyPhraseBatchResultItem withStatistics(DocumentStatistics statistics) {
        this.statistics = statistics;
        return this;
    }

}
