/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.cognitiveservices.language.textanalytics.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The LanguageBatchResultItem model.
 */
public class LanguageBatchResultItem {
    /**
     * Unique, non-empty document identifier.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * A list of extracted languages.
     */
    @JsonProperty(value = "detectedLanguages")
    private List<DetectedLanguage> detectedLanguages;

    /**
     * (Optional) if showStats=true was specified in the request this field
     * will contain information about the document payload.
     */
    @JsonProperty(value = "statistics")
    private DocumentStatistics statistics;

    /**
     * Get unique, non-empty document identifier.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set unique, non-empty document identifier.
     *
     * @param id the id value to set
     * @return the LanguageBatchResultItem object itself.
     */
    public LanguageBatchResultItem withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get a list of extracted languages.
     *
     * @return the detectedLanguages value
     */
    public List<DetectedLanguage> detectedLanguages() {
        return this.detectedLanguages;
    }

    /**
     * Set a list of extracted languages.
     *
     * @param detectedLanguages the detectedLanguages value to set
     * @return the LanguageBatchResultItem object itself.
     */
    public LanguageBatchResultItem withDetectedLanguages(List<DetectedLanguage> detectedLanguages) {
        this.detectedLanguages = detectedLanguages;
        return this;
    }

    /**
     * Get (Optional) if showStats=true was specified in the request this field will contain information about the document payload.
     *
     * @return the statistics value
     */
    public DocumentStatistics statistics() {
        return this.statistics;
    }

    /**
     * Set (Optional) if showStats=true was specified in the request this field will contain information about the document payload.
     *
     * @param statistics the statistics value to set
     * @return the LanguageBatchResultItem object itself.
     */
    public LanguageBatchResultItem withStatistics(DocumentStatistics statistics) {
        this.statistics = statistics;
        return this;
    }

}
