/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.cognitiveservices.language.textanalytics.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The RequestStatistics model.
 */
public class RequestStatistics {
    /**
     * Number of documents submitted in the request.
     */
    @JsonProperty(value = "documentsCount")
    private Integer documentsCount;

    /**
     * Number of valid documents. This excludes empty, over-size limit or
     * non-supported languages documents.
     */
    @JsonProperty(value = "validDocumentsCount")
    private Integer validDocumentsCount;

    /**
     * Number of invalid documents. This includes empty, over-size limit or
     * non-supported languages documents.
     */
    @JsonProperty(value = "erroneousDocumentsCount")
    private Integer erroneousDocumentsCount;

    /**
     * Number of transactions for the request.
     */
    @JsonProperty(value = "transactionsCount")
    private Long transactionsCount;

    /**
     * Get number of documents submitted in the request.
     *
     * @return the documentsCount value
     */
    public Integer documentsCount() {
        return this.documentsCount;
    }

    /**
     * Set number of documents submitted in the request.
     *
     * @param documentsCount the documentsCount value to set
     * @return the RequestStatistics object itself.
     */
    public RequestStatistics withDocumentsCount(Integer documentsCount) {
        this.documentsCount = documentsCount;
        return this;
    }

    /**
     * Get number of valid documents. This excludes empty, over-size limit or non-supported languages documents.
     *
     * @return the validDocumentsCount value
     */
    public Integer validDocumentsCount() {
        return this.validDocumentsCount;
    }

    /**
     * Set number of valid documents. This excludes empty, over-size limit or non-supported languages documents.
     *
     * @param validDocumentsCount the validDocumentsCount value to set
     * @return the RequestStatistics object itself.
     */
    public RequestStatistics withValidDocumentsCount(Integer validDocumentsCount) {
        this.validDocumentsCount = validDocumentsCount;
        return this;
    }

    /**
     * Get number of invalid documents. This includes empty, over-size limit or non-supported languages documents.
     *
     * @return the erroneousDocumentsCount value
     */
    public Integer erroneousDocumentsCount() {
        return this.erroneousDocumentsCount;
    }

    /**
     * Set number of invalid documents. This includes empty, over-size limit or non-supported languages documents.
     *
     * @param erroneousDocumentsCount the erroneousDocumentsCount value to set
     * @return the RequestStatistics object itself.
     */
    public RequestStatistics withErroneousDocumentsCount(Integer erroneousDocumentsCount) {
        this.erroneousDocumentsCount = erroneousDocumentsCount;
        return this;
    }

    /**
     * Get number of transactions for the request.
     *
     * @return the transactionsCount value
     */
    public Long transactionsCount() {
        return this.transactionsCount;
    }

    /**
     * Set number of transactions for the request.
     *
     * @param transactionsCount the transactionsCount value to set
     * @return the RequestStatistics object itself.
     */
    public RequestStatistics withTransactionsCount(Long transactionsCount) {
        this.transactionsCount = transactionsCount;
        return this;
    }

}
