/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.cognitiveservices.language.textanalytics.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SentimentBatchResultItem model.
 */
public class SentimentBatchResultItem {
    /**
     * Unique, non-empty document identifier.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * A decimal number between 0 and 1 denoting the sentiment of the document.
     * A score above 0.7 usually refers to a positive document while a score
     * below 0.3 normally has a negative connotation. Mid values refer to
     * neutral text.
     */
    @JsonProperty(value = "score")
    private Double score;

    /**
     * (Optional) if showStats=true was specified in the request this field
     * will contain information about the document payload.
     */
    @JsonProperty(value = "statistics")
    private DocumentStatistics statistics;

    /**
     * Get unique, non-empty document identifier.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set unique, non-empty document identifier.
     *
     * @param id the id value to set
     * @return the SentimentBatchResultItem object itself.
     */
    public SentimentBatchResultItem withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get a decimal number between 0 and 1 denoting the sentiment of the document. A score above 0.7 usually refers to a positive document while a score below 0.3 normally has a negative connotation. Mid values refer to neutral text.
     *
     * @return the score value
     */
    public Double score() {
        return this.score;
    }

    /**
     * Set a decimal number between 0 and 1 denoting the sentiment of the document. A score above 0.7 usually refers to a positive document while a score below 0.3 normally has a negative connotation. Mid values refer to neutral text.
     *
     * @param score the score value to set
     * @return the SentimentBatchResultItem object itself.
     */
    public SentimentBatchResultItem withScore(Double score) {
        this.score = score;
        return this;
    }

    /**
     * Get (Optional) if showStats=true was specified in the request this field will contain information about the document payload.
     *
     * @return the statistics value
     */
    public DocumentStatistics statistics() {
        return this.statistics;
    }

    /**
     * Set (Optional) if showStats=true was specified in the request this field will contain information about the document payload.
     *
     * @param statistics the statistics value to set
     * @return the SentimentBatchResultItem object itself.
     */
    public SentimentBatchResultItem withStatistics(DocumentStatistics statistics) {
        this.statistics = statistics;
        return this;
    }

}
